name: build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Go Building
        run: |
          go env
          go get -u golang.org/x/lint/golint
          go test -v -race ./...
          go vet ./...
          golint ./...
          go build main.go
